# Form implementation generated from reading ui file 'c:\Users\facur\OneDrive\Documentos\AAA UTN\Proyecto Final Digitalizacion Minutas\ui\menu.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(885, 592)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setEnabled(True)
        self.centralwidget.setMinimumSize(QtCore.QSize(500, 0))
        self.centralwidget.setBaseSize(QtCore.QSize(200, 0))
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.frame = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(180, 0))
        self.frame.setMaximumSize(QtCore.QSize(180, 16777215))
        self.frame.setStyleSheet("/* Color del fondo del menú lateral */\n"
"QFrame#frame {\n"
"    background-color: rgb(114, 190, 250);\n"
"}\n"
"\n"
"/* Estilo para todos los botones que están adentro del menú */\n"
"QPushButton {\n"
"    background-color: transparent;\n"
"    color: black;\n"
"    font-size: 14px;\n"
"    font-weight: bold;\n"
"    border: none;\n"
"    padding: 10px;\n"
"}\n"
"\n"
"/* Efecto cuando pasás el mouse por encima del botón */\n"
"QPushButton:hover {\n"
"    background-color: rgba(255, 255, 255, 50);\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame.setObjectName("frame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.frame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(-10, 10, 301, 571))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 50, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.btn_home = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_home.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_home.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_home.setFont(font)
        self.btn_home.setStyleSheet("background-color: rgb(255, 255, 255);\n"
"")
        self.btn_home.setText("INICIO")
        self.btn_home.setObjectName("btn_home")
        self.verticalLayout.addWidget(self.btn_home)
        self.btn_clientes = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_clientes.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_clientes.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_clientes.setFont(font)
        self.btn_clientes.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_clientes.setObjectName("btn_clientes")
        self.verticalLayout.addWidget(self.btn_clientes)
        self.btn_inmuebles = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_inmuebles.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_inmuebles.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_inmuebles.setFont(font)
        self.btn_inmuebles.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_inmuebles.setObjectName("btn_inmuebles")
        self.verticalLayout.addWidget(self.btn_inmuebles)
        self.btn_minutas = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_minutas.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_minutas.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_minutas.setFont(font)
        self.btn_minutas.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_minutas.setObjectName("btn_minutas")
        self.verticalLayout.addWidget(self.btn_minutas)
        self.btn_cerrar = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        self.btn_cerrar.setMinimumSize(QtCore.QSize(200, 0))
        self.btn_cerrar.setMaximumSize(QtCore.QSize(200, 16777215))
        font = QtGui.QFont()
        font.setPointSize(-1)
        font.setBold(True)
        font.setWeight(75)
        self.btn_cerrar.setFont(font)
        self.btn_cerrar.setStyleSheet("background-color: rgb(255, 255, 255);")
        self.btn_cerrar.setObjectName("btn_cerrar")
        self.verticalLayout.addWidget(self.btn_cerrar)
        self.horizontalLayout.addWidget(self.frame)
        self.contendor_paginas = QtWidgets.QStackedWidget(parent=self.centralwidget)
        self.contendor_paginas.setObjectName("contendor_paginas")
        self.INICIO = QtWidgets.QWidget()
        self.INICIO.setObjectName("INICIO")
        self.contendor_paginas.addWidget(self.INICIO)
        self.CLIENTES = QtWidgets.QWidget()
        self.CLIENTES.setObjectName("CLIENTES")
        self.contendor_paginas.addWidget(self.CLIENTES)
        self.INMUEBLES = QtWidgets.QWidget()
        self.INMUEBLES.setObjectName("INMUEBLES")
        self.contendor_paginas.addWidget(self.INMUEBLES)
        self.MINUTAS = QtWidgets.QWidget()
        self.MINUTAS.setObjectName("MINUTAS")
        self.contendor_paginas.addWidget(self.MINUTAS)
        self.horizontalLayout.addWidget(self.contendor_paginas)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.contendor_paginas.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.btn_clientes.setText(_translate("MainWindow", "CLIENTES"))
        self.btn_inmuebles.setText(_translate("MainWindow", "INMUEBLES"))
        self.btn_minutas.setText(_translate("MainWindow", "MINUTAS"))
        self.btn_cerrar.setText(_translate("MainWindow", "CERRAR SESION"))
