# Form implementation generated from reading ui file 'c:\Users\facur\OneDrive\Documentos\AAA UTN\Proyecto Final Digitalizacion Minutas\ui\ventana_ph.ui'
#
# Created by: PyQt6 UI code generator 6.11.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_DatosPH(object):
    def setupUi(self, DatosPH):
        DatosPH.setObjectName("DatosPH")
        DatosPH.resize(400, 300)
        self.gridLayoutWidget = QtWidgets.QWidget(parent=DatosPH)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(17, 20, 371, 261))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.txt_ph_porcentaje = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txt_ph_porcentaje.setObjectName("txt_ph_porcentaje")
        self.gridLayout.addWidget(self.txt_ph_porcentaje, 2, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.btn_aceptar_ph = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(10)
        font.setBold(True)
        font.setWeight(75)
        self.btn_aceptar_ph.setFont(font)
        self.btn_aceptar_ph.setObjectName("btn_aceptar_ph")
        self.gridLayout.addWidget(self.btn_aceptar_ph, 3, 0, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.txt_ph_unidad = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txt_ph_unidad.setObjectName("txt_ph_unidad")
        self.gridLayout.addWidget(self.txt_ph_unidad, 0, 1, 1, 1)
        self.txt_ph_poligono = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        self.txt_ph_poligono.setObjectName("txt_ph_poligono")
        self.gridLayout.addWidget(self.txt_ph_poligono, 1, 1, 1, 1)

        self.retranslateUi(DatosPH)
        QtCore.QMetaObject.connectSlotsByName(DatosPH)

    def retranslateUi(self, DatosPH):
        _translate = QtCore.QCoreApplication.translate
        DatosPH.setWindowTitle(_translate("DatosPH", "Dialog"))
        self.label_2.setText(_translate("DatosPH", "Poligono"))
        self.label_3.setText(_translate("DatosPH", "Porcentaje Indeviso"))
        self.btn_aceptar_ph.setText(_translate("DatosPH", "Aceptar"))
        self.label.setText(_translate("DatosPH", "Unidad Funcional"))
